import { useState } from 'react';

const image = 'https://lh3.googleusercontent.com/aida/';
const pillars = [
  ['01 / Quality', 'Uncompromising sourcing standards, calibrated moisture metrics, and multi-stage testing across all lots.'],
  ['02 / Authenticity', 'Genuine origins, unadulterated ingredients, and direct multigenerational orchard partnerships.'],
  ['03 / Thoughtful Selection', 'Curated for palate equilibrium, balanced textures, and rich natural vitality without synthetic shortcuts.'],
  ['04 / Product Variety', 'A rich multi-category portfolio spanning heirloom nuts, solar dried harvests, botanical seeds, and snacks.'],
  ['05 / Everyday Goodness', 'Wholesome, clean nourishment designed for daily desks, family tables, and mindful breaks.'],
  ['06 / Customer Trust', 'Airtight protective packaging preserving natural freshness from grove to corporate or domestic table.'],
];
const categories = [
  ['01 / Reserve', 'Dates', 'Naturally rich, succulent caramel notes straight from ancient desert oasis palms.'],
  ['02 / Crunch', 'Nuts', 'Golden roasted almonds, whole cashews, mountain walnuts, and green pistachios.'],
  ['03 / Essence', 'Dry Fruits', 'Naturally sweet, solar-cured figs, wild cranberries, and golden sultanas.'],
  ['04 / Vitality', 'Seeds', 'Dense botanical nourishment: chia, golden pumpkin, sesame, and flax.'],
  ['05 / Indulgence', 'Chocolates', 'Single-origin stone-ground dark chocolate truffles with roasted nut inserts.'],
  ['06 / Aroma', 'Spices', 'Artisanal whole green cardamom, royal saffron threads, and Ceylon cinnamon.'],
  ['07 / Everyday', 'Snacks', 'Slow vacuum-roasted savoury snacks seasoned with pink Himalayan salt.'],
  ['08 / Elixirs', 'Beverages', 'Cold-pressed botanical infusions and high mountain herbal tisanes.'],
  ['09 / Terroir', 'Imported Delights', 'Curated delicacies sourced directly from Mediterranean and Andean groves.'],
  ['10 / Texture', 'Munchies', 'Crisp baked treats crafted with whole grains and natural botanical herbs.'],
];

function Arrow() { return <span className="material-symbols-outlined">arrow_forward</span>; }
function Label({ children, dark = false }) { return <span className={`about-label ${dark ? 'about-label-light' : ''}`}>{children}</span>; }

export default function About() {
  const [submitted, setSubmitted] = useState(false);
  return <main className="about-reference">
    <section className="about-hero"><div className="about-lines" /><svg className="about-hero-curves" aria-hidden="true" fill="none" preserveAspectRatio="none" viewBox="0 0 1440 600"><path d="M-100 450 C 300 200, 700 600, 1100 320 C 1300 180, 1500 390, 1600 300" stroke="#50CD65" strokeDasharray="6 6" strokeWidth="1.2" /><path d="M-100 350 C 250 150, 650 500, 1050 250 C 1280 120, 1450 330, 1600 250" stroke="#9EFFAD" strokeWidth="0.8" /><circle cx="1050" cy="250" fill="#9EFFAD" r="3" /><circle cx="700" cy="600" fill="#50CD65" r="2" /></svg><div className="about-container"><div className="about-hero-pill"><i /> The Frudex Story &amp; Ethos</div><div className="about-hero-grid"><div><h1>Goodness,<br /><em>Selected</em> With Purpose.</h1><p>Frudex brings together quality food products, thoughtful selection, and everyday enjoyment. Rooted in integrity and crafted for conscious living, we curate the finest harvest for moments that matter.</p><div className="about-actions"><a className="about-button" href="#philosophy">Explore Our Philosophy <span>↓</span></a><a className="about-outline" href="#pillars">Six Core Pillars</a></div><div className="about-metrics"><div><strong>100%</strong><span>Single Origin Traceable</span></div><div><strong>11+</strong><span>Master Categories</span></div><div><strong>Zero</strong><span>Synthetic Additives</span></div></div></div><div className="about-hero-card"><img alt="Editorial gourmet dates, almonds, pistachios and walnuts on deep emerald marble" src="https://lh3.googleusercontent.com/aida/AEtjO1UllZThjmM0IIM3tHsNy9AM6UC6YU2IQ0gGVpU9-g5tzEddZoZcvaiV8qqKOx6z11dYgMWuIWs06qAvBjYYZAQNXNJBEgPLZvf2ItMdC0e3aokqxA-CC_btyRNqrOABnPNyZqBnnWCcaiAlf1rAUCWL5nbRq1aaI_iXrlad0oKuhVZDDT_watrZV_bTLazVM0kzL5Fu0DI2j_oYApeRYQPgPVDSmz3eTOH1IH_NZFjGGyZTuMiiDtKWOYc" /><div><Label dark>Harvest Dossier 01</Label><strong>Medjool Date &amp; Pistachio Reserve</strong><span>100% Traceable</span></div></div></div></div></section>
    <section className="about-philosophy" id="philosophy"><div className="about-container about-split"><div><Label>Philosophy &amp; Provenance</Label><h2>An unhurried devotion to the world&apos;s most <em>pristine harvests.</em></h2><p className="about-lead">Frudex was conceived at the intersection of agricultural respect and culinary pleasure. We believe that everyday food should elevate ordinary routines into sensory milestones.</p><p>Rather than industrial consolidation, our procurement operates on micro-climates, seasonal cycles, and patient curing. Every single date, nut cluster, and confection is treated with unhurried discernment, preserving authentic oils, delicate sugars, and structural crunch.</p><div className="about-pillars" id="pillars"><h3>Our Six Core Pillars</h3><div>{pillars.map(([title, text]) => <article key={title}><Label>{title}</Label><p>{text}</p></article>)}</div></div></div><div className="about-showcase"><img alt="Gourmet flatlay of dates, nuts and chocolate" src={`${image}AEtjO1W-Gip0Q8Rr4Ve97REPwyvEmS_OwqOCWbClH2lGSC_BLc0NdpB3zAp-QkMF5tqv46bN_PrM6pVITXVPlXzNMV0_sTZYKEOn3YlXWPVpv9OuRO1oqsB4lZCByESAJ1_dBNwOeLQVfSnE12bzT5gNFdEGEzr58lbku4sJ-rN8EvjcIZY1Pi0H4HDDd4aiS-WKOhrdB7OLMK_caowDALMeY7DtsRWFUApZrTXi6ZkLfUxgS0cWgaCAMM1IoH0`} /><div><strong>The Curated Harvest</strong><span>Botanical classifications. 004 / Orchard selection.</span><b>Direct Estate</b></div></div></div></section>
    <section className="about-principles"><div className="about-container"><div className="about-centered"><Label>Our Quality Standard</Label><h2>Three Guiding Principles</h2><p>How our philosophy translates from raw branch and grove directly into daily sensory enrichment.</p></div><div className="principle-grid">{[['search', 'The Art of Selection', 'We practice slow curation. Only mature trees under balanced hydrological cycles qualify for harvest.', 'Zero shortcuts • Slow curation'], ['wb_sunny', 'Natural Purity', 'Zero chemical polishing, synthetic humectants, or artificial essences. We allow each terroir to speak.', 'Unadulterated • Chemical Free'], ['verified', 'Daily Elevation', 'Haute snacking should not remain confined to celebratory banquets. We package provisions for daily rituals.', 'Hermetic preservation • Everyday luxury']].map(([icon, title, text, footer], index) => <article key={title}><span className="principle-icon material-symbols-outlined">{icon}</span><Label>Principle 0{index + 1}</Label><h3>{title}</h3><p>{text}</p><footer>{footer}</footer></article>)}</div></div></section>
    <section className="about-portfolio"><div className="about-container"><div className="portfolio-heading"><div><Label>• Comprehensive FMCG Range</Label><h2>More Than Just Dry Fruits.</h2><p>A carefully selected world of flavour, goodness, and everyday indulgence across eleven distinct harvest chapters.</p></div><div><Label>Collection Index</Label><strong>11 Master Categories</strong></div></div><div className="category-grid">{categories.map(([number, title, text]) => <article key={title}><Label>{number}</Label><h3>{title}</h3><p>{text}</p><a href="/products">Explore Notes <Arrow /></a></article>)}<article className="category-feature"><Label dark>11 / Bespoke</Label><h3>Gift Box &amp; Hampers</h3><p>Thoughtfully packed. Made to be shared. Prestige presentation boxes, embossed wood keepsakes, and artisanal corporate hampers.</p><a href="#inquiry">Explore Bespoke Gifting Service <Arrow /></a></article></div></div></section>
    <section className="about-journey"><div className="about-container"><div className="about-centered"><Label dark>• The Quality Journey</Label><h2>From Selection To <em>Your Everyday.</em></h2><p>A four-stage continuum safeguarding nutritional integrity, pristine flavour profiles, and tactile pleasure.</p></div><div className="journey-grid">{[['01', 'Selected', 'Hand-picked grades calibrated for optimal ripeness, uniform calibre, and peak harvest seasonality.', 'Origin Terroir'], ['02', 'Quality Check', 'Multi-stage inspection, laser-assisted optical sorting, and internal lab sensory validation protocols.', 'Lab Standards'], ['03', 'Carefully Packed', 'Hermetic nitrogen-flushed seal barriers preserving oils, aromas, and crispness without preservatives.', 'Freshness Lock'], ['04', 'Ready to Enjoy', 'Wholesome nourishment and refined gastronomy delivered seamlessly to discerning kitchens worldwide.', 'Table Grace']].map(([number, title, text, phase]) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{text}</p><span>{phase}</span></article>)}</div></div></section>
    <section className="about-packaging"><div className="about-container packaging-split"><div><Label>Aesthetic Integrity</Label><h2>Goodness Worth <em>Sharing.</em></h2><p>Our packaging philosophy mirrors our culinary standards: tactile luxury, understated forest greens, and materials that preserve nature&apos;s bounty with dignity.</p><p>From FSC-certified matte cardstock to double-walled gold-embossed presentation tins, every container is designed to dwell gracefully on coffee tables, executive desks, and banquet spreads.</p><ul><li>Hermetic Oxygen Barriers for Peak Crispness</li><li>Bespoke Gold Foil Calligraphy &amp; Minimal Typography</li><li>Reusable Rigid Keepsake Gift Cases</li></ul></div><div className="packaging-specs"><article><span className="material-symbols-outlined">inventory_2</span><h3>Signature Reserve Pouch</h3><p>Multi-barrier film with matte velvet touch and zip preservation seal.</p></article><article><span className="material-symbols-outlined">menu_book</span><h3>Prestige Celebration Box</h3><p>Rigid keepsake book-box with satin pull ribbon and embossed typography.</p></article></div></div></section>
    <section className="about-credo"><div className="credo-rings" /><div className="about-container"><Label dark>• The Botanical Horizon •</Label><blockquote>“True food integrity is not engineered in a laboratory. It is discovered in healthy soil, nurtured by experienced hands, and curated without compromise for families who value honest nourishment.”</blockquote><strong>The Frudex Selection Council</strong><span>Provence • California • Caspian Basin • Madinah</span></div></section>
    <section className="about-contact" id="inquiry"><div className="about-container contact-split"><div><Label>Direct Channel</Label><h2>Let&apos;s Connect.</h2><p>Have a question, business enquiry or want to know more about Frudex? We&apos;d love to hear from you.</p><div className="contact-copy"><p><strong>Head Office &amp; Reserve Center</strong><br />Frudex Global FMCG Agri-Ventures, Botanical Quality Labs, Suites 401-404</p><p><strong>Business &amp; Distribution Inquiries</strong><br />partnerships@frudex.com</p><p><strong>Trade Desk</strong><br />+1 (800) 442-3782 / +44 20 7149 0912</p></div><div className="contact-callout"><b>Corporate &amp; Executive Hampers</b><br />For custom volume gifting, bespoke embossing, or private label concierge accounts, please indicate your acquisition volume in the inquiry message.</div></div><form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><h3>Submit a Corporate Enquiry</h3><div className="form-grid"><label>Full Name<input required placeholder="e.g. Lord Alistair Vance" /></label><label>Corporate / Personal Email<input required placeholder="name@organization.com" type="email" /></label><label>Phone Number<input placeholder="+44 20 ..." /></label><label>Enquiry Type<select defaultValue="retail"><option value="retail">Retail Distribution &amp; Stockist</option><option value="gifting">Corporate Gifting &amp; Executive Hampers</option><option value="supply">Institutional Food Service Supply</option></select></label></div><label>Your Message<textarea placeholder="Please outline your inquiry, estimated quantities, or regional requirements..." rows="4" /></label><button type="submit">Send Inquiry →</button>{submitted && <p className="form-success">Thank you. Your inquiry has been received.</p>}</form></div></section>
  </main>;
}
