import { useState } from 'react';
import { Link } from 'react-router-dom';

const image = 'https://lh3.googleusercontent.com/aida/';
const pillars = [
  ['01 / Quality', 'We check every batch carefully for moisture, freshness, and quality.'],
  ['02 / Authenticity', 'Real ingredients from trusted growers we know well.'],
  ['03 / Thoughtful Selection', 'Chosen for great taste and texture, with nothing artificial.'],
  ['04 / Product Variety', 'A wide range of products — nuts, dried fruits, seeds, and snacks.'],
  ['05 / Everyday Goodness', 'Healthy, simple food for everyday life — at work, at home, anytime.'],
  ['06 / Customer Trust', 'Sealed packaging keeps everything fresh until it reaches you.'],
];
const categories = [
  ['01 / Reserve', 'Dates', 'Rich, sweet dates with a natural caramel taste.', 'dates'],
  ['02 / Crunch', 'Nuts', 'Golden roasted almonds, whole cashews, mountain walnuts, and green pistachios.', 'nuts'],
  ['03 / Essence', 'Dry Fruits', 'Naturally sweet dried figs, cranberries, and golden raisins.', 'dry-fruits'],
  ['04 / Vitality', 'Seeds', 'Healthy seeds: chia, pumpkin, sesame, and flax.', 'seeds'],
  ['05 / Indulgence', 'Chocolates', 'Rich dark chocolate truffles with roasted nuts inside.', 'chocolates'],
  ['06 / Aroma', 'Spices', 'Whole green cardamom, saffron threads, and Ceylon cinnamon.', 'spices'],
  ['07 / Everyday', 'Snacks', 'Crunchy roasted snacks seasoned with Himalayan salt.', 'snacks'],
  ['08 / Elixirs', 'Beverages', 'Cold-pressed drinks and herbal teas.', 'beverages'],
  ['09 / Terroir', 'Imported Delights', 'Specialty foods sourced from around the world.', 'imported-specialties'],
  ['10 / Texture', 'Munchies', 'Crispy baked snacks made with whole grains and herbs.', 'munchies'],
];

function Arrow() { return <span className="material-symbols-outlined">arrow_forward</span>; }
function Label({ children, dark = false }) { return <span className={`about-label ${dark ? 'about-label-light' : ''}`}>{children}</span>; }

export default function About() {
  const [submitted, setSubmitted] = useState(false);
  return <main className="about-reference">
    <section className="about-hero"><div className="about-lines" /><svg className="about-hero-curves" aria-hidden="true" fill="none" preserveAspectRatio="none" viewBox="0 0 1440 600"><path className="hero-linework-dash" d="M-100 450 C 300 200, 700 600, 1100 320 C 1300 180, 1500 390, 1600 300" stroke="#50CD65" strokeDasharray="6 6" strokeWidth="1.2" /><path d="M-100 350 C 250 150, 650 500, 1050 250 C 1280 120, 1450 330, 1600 250" stroke="#9EFFAD" strokeWidth="0.8" /><circle cx="1050" cy="250" fill="#9EFFAD" r="3" /><circle cx="700" cy="600" fill="#50CD65" r="2" /></svg><div className="about-container"><div className="about-hero-pill"><i /> Our Story</div><div className="about-hero-grid"><div><h1>Goodness,<br /><em>Selected</em> With Purpose.</h1><p>Frudex brings together quality food you can enjoy every day. We carefully choose every product so you get the best, every time.</p><div className="about-actions"><a className="about-button" href="#philosophy">Learn About Us <span>↓</span></a><a className="about-outline" href="#pillars">Our Values</a></div><div className="about-metrics"><div><strong>100%</strong><span>Traceable Sourcing</span></div><div><strong>11+</strong><span>Product Categories</span></div><div><strong>Zero</strong><span>Synthetic Additives</span></div></div></div><div className="about-hero-card"><img alt="Editorial gourmet dates, almonds, pistachios and walnuts on deep emerald marble" src="/images/About_page.png" /><div><Label dark>Featured Product</Label><span>100% Traceable</span></div></div></div></div></section>
    <section className="about-philosophy" id="philosophy"><div className="about-container about-split"><div><Label>Our Story</Label><h2>We care deeply about <em>quality ingredients.</em></h2><p className="about-lead">Frudex started with a simple idea — good food should be part of everyday life, not just special occasions.</p><p>We don&apos;t rush. We choose our dates, nuts, and sweets carefully by season and region, keeping their natural taste, oils, and crunch intact.</p><div className="about-pillars" id="pillars"><h3>Our Values</h3><div>{pillars.map(([title, text]) => <article key={title}><Label>{title}</Label><p>{text}</p></article>)}</div></div></div><div className="about-showcase"><img alt="Gourmet flatlay of dates, nuts and chocolate" src="/images/Pistachios.png"/><div><strong>Our Selection</strong></div></div></div></section>
    <section className="about-principles"><div className="about-container"><div className="about-centered"><Label>Our Quality Standard</Label><h2>Three Guiding Principles</h2><p>How we turn good ingredients into everyday enjoyment.</p></div><div className="principle-grid">{[['search', 'The Art of Selection', 'We take our time. Only the best, ripest fruit makes it into our selection.', 'No shortcuts • Careful selection'], ['wb_sunny', 'Natural Purity', 'No chemical treatments or artificial flavours. Just natural taste.', 'Unadulterated • Chemical Free'], ['verified', 'Daily Elevation', 'Great snacks shouldn\'t be just for special occasions. We make ours easy to enjoy every day.', 'Stays fresh • Everyday enjoyment']].map(([icon, title, text, footer], index) => <article key={title}><span className="principle-icon material-symbols-outlined">{icon}</span><Label>Principle 0{index + 1}</Label><h3>{title}</h3><p>{text}</p><footer>{footer}</footer></article>)}</div></div></section>
    <section className="about-portfolio"><div className="about-container"><div className="portfolio-heading"><div><Label>• Our Product Range</Label><h2>More Than Just Dry Fruits.</h2><p>Explore all 11 categories of Frudex products.</p></div><div><Label>Categories</Label><strong>11 Categories</strong></div></div><div className="category-grid">{categories.map(([number, title, text, slug]) => <article key={title}><Label>{number}</Label><h3>{title}</h3><p>{text}</p><Link to={`/products/${slug}`}>Explore <Arrow /></Link></article>)}<article className="category-feature"><Label dark>11 / Bespoke</Label><h3>Gift Box &amp; Hampers</h3><p>Thoughtfully packed and made to be shared. Elegant gift boxes and hampers for any occasion.</p><Link to="/products/gift-boxes-hampers">Explore Gifting <Arrow /></Link></article></div></div></section>
    <section className="about-journey"><div className="about-container"><div className="about-centered"><Label dark>• The Quality Journey</Label><h2>From Selection To <em>Your Everyday.</em></h2><p>Four simple steps that keep every product fresh and tasty.</p></div><div className="journey-grid">{[['01', 'Selected', 'We hand-pick each item at the right time for the best size and ripeness.', 'Farm Origin'], ['02', 'Quality Check', 'Every batch is checked and tested for quality.', 'Lab Tested'], ['03', 'Carefully Packed', 'Sealed packaging keeps everything fresh and crunchy, with no preservatives.', 'Stays Fresh'], ['04', 'Ready to Enjoy', 'Delivered fresh and ready for you to enjoy.', 'Ready to Eat']].map(([number, title, text, phase]) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{text}</p><span>{phase}</span></article>)}</div></div></section>
    <section className="about-packaging"><div className="about-container packaging-split"><div><Label>Our Packaging</Label><h2>Goodness Worth <em>Sharing.</em></h2><p>We pack our products with the same care we put into choosing them — quality materials that keep everything fresh and look great too.</p><p>From eco-friendly cardboard to elegant gift tins, every pack looks great anywhere — at home, at work, or as a gift.</p><ul><li>Sealed Packs Keep Food Fresh &amp; Crunchy</li><li>Elegant, Simple Design</li><li>Sturdy Boxes You Can Reuse</li></ul></div><div className="packaging-specs"><article><span className="material-symbols-outlined">inventory_2</span><h3>Signature Reserve Pouch</h3><p>A soft-touch pouch with a resealable zip that keeps food fresh.</p></article><article><span className="material-symbols-outlined">menu_book</span><h3>Prestige Celebration Box</h3><p>A sturdy gift box with a ribbon pull, great for gifting.</p></article></div></div></section>
    <section className="about-credo"><div className="credo-rings" /><div className="about-container"><Label dark>• Our Promise •</Label><blockquote>“Good food isn&apos;t made in a lab. It comes from healthy soil, careful hands, and an honest promise to every family we serve.”</blockquote></div></section>
    <section className="about-contact" id="inquiry"><div className="about-container contact-split"><div><Label>Direct Channel</Label><h2>Let&apos;s Connect.</h2><p>Have a question, business enquiry or want to know more about Frudex? We&apos;d love to hear from you.</p><div className="contact-copy"><p><strong>Head Office</strong><br />N.I.T Road, Chundappuram, Koduvally, Kozhikode 673572, Kerala, India</p><p><strong>Business &amp; Distribution Inquiries</strong><br /><a href="mailto:frudexdryfruits@gmail.com">frudexdryfruits@gmail.com</a></p><p><strong>Trade Desk</strong><br /><a href="tel:+918129555591">+91 81295 55591</a></p></div><div className="contact-callout"><b>Corporate &amp; Bulk Gifting</b><br />For bulk gifting, custom branding, or private label orders, just mention your quantity in the message below.</div></div><form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><h3>Send Us a Message</h3><div className="form-grid"><label>Full Name<input name="Full Name" required placeholder="e.g. Ahmed Khan" /></label><label>Email Address<input name="Email" required placeholder="you@example.com" type="email" /></label><label>Phone Number<input name="Phone" placeholder="+91 81295 55591" /></label><label>Enquiry Type<select defaultValue="retail" name="Enquiry Type"><option value="retail">Retail / Stockist</option><option value="gifting">Corporate Gifting</option><option value="supply">Bulk / Wholesale Supply</option></select></label></div><label>Your Message<textarea name="Message" placeholder="Tell us what you need — product, quantity, and delivery location..." rows="4" /></label><button type="submit">Send Inquiry →</button>{submitted && <p className="form-success">Thank you! We&apos;ve received your message and will get back to you soon.</p>}</form></div></section>
  </main>;
}
