import { useState } from 'react';
import { Link } from 'react-router-dom';

const imageBase = 'https://lh3.googleusercontent.com/aida-public/';
const products = [
  ['01 / Reserve', 'Origin: Jordan Valley', 'DATES', 'Naturally rich. Naturally delicious. Succulent caramel notes straight from ancient desert palms.', 'AB6AXuCWXAqIZ2qs-raKcU5NMSZy6KrM0U9lYPqixi6rWuHzP8ELHcCmCsxMTBkNQEF37Y0-dQpefpTbSwY3J5bgS2TcfX63oUE2qB0J1-ZLGDVBHcmAb2V29RhMRElpfMEjwu2L3NPItCquvskNM2uY4_qEvn42dSispRZDMpNXGdYiL-Y8ZSGdp7dIRqAjSBFBja61Bnj4KXZm-z67RZ-ukv5Bmm_n54mMQxgjpUqFD0ta6__Q-hhkhi79Wg'],
  ['02 / Crunch', 'Origin: Multi-Region', 'NUTS', 'Wholesome crunch, thoughtfully selected. Golden roasted almonds, cashews, pistachios, and walnuts.', 'AB6AXuB02L1IPcHkyoB8ubvHu8pl1l_Di1rGVTxxL-H7GtoLnh261iIhMidf3cGmpW3p1yazPg_iyCTFw7EeVD-dX7M1Id8YTiTib2enTO4VV_fn1LT1JjwHVxb04T19KFlgfFEOluj033sGMvOrqJZVwnpPj_RUFPMIAsflWj5D0XhHo0vKaFAdTel7m3Vgyu66VnkdMSeauHvMM4XFk84B2_z9h3KqxD-yiV6sG436uZDj2yYx6SXxc9Ljwg'],
  ['03 / Essence', 'Origin: Sun-Dried', 'DRY FRUITS', 'Naturally sweet. Beautifully satisfying. Concentrated nectar and solar-cured texture in every harvest.', 'AB6AXuCV9aT0yyje0tqpXEScqWqKYyi-07fCNTE3qrDcnOixNZAicwnKZ9fUwT7H-Y2_hYNGAa-gg-d2EkTvBM__Jm8tpsqWDLMbmhmd48OSOVPcGZkBV8OaiEwi2dHDp98u6oHSG8cXMQvLs2ZcpZoS0bSpJynvkDLXz6tXoQX8s6t8lY23LaXjqargml7kEdpC14yydRTTZRcTwv_3Npb5MPOScT2icuy_FOgULCzEGdUVt3EuF8hQAKqTJg'],
  ['04 / Vitality', 'Origin: Raw & Roasted', 'SEEDS', 'Small in size. Big on goodness. Dense botanical nourishment and earthy texture for purposeful rituals.', 'AB6AXuDXo968KVfHBnTTdr4HoMpiGstb_Vz1S3GR0H1907KqPH6bE0D6hlUFYel96-ajJ9Xf0EEotiRD5HhqvGZXLSiSWlOmqAXt9rbmwaLl2GKRubt5Er43QqJ56Wv_qweDqsVXhGzjMWEPEsslL9SzWztP2qWUZYfK6OMWuWBBp2b-cjv9Ld0EWK9xlgOvwe3_vaelErgwjK_EKBUk4SGR-JWlyFNOwYXgmQECxQFzOjhimLdMgI9mpM_G-g'],
];
const secondaryProducts = ['CHOCOLATES', 'SPICES', 'SNACKS', 'BEVERAGES'];
const moments = [
  ['Morning Ritual', 'Breakfast & Sustained Energy', '/images/breakfast.png'],
  ['Mid-day Focus', 'Executive & Work Balance', '/images/work.png'],
  ['Evening Gathering', 'Family & Celebrations', '/images/family.png'],
  ['Generosity', 'Festive Gifting & Sharing', '/images/Gift.png'],
  ['Host Gastronomy', 'Entertaining with Elegance', '/images/elegent.png'],
  ['Mobility', 'On-The-Go Snacking', '/images/travel.png'],
];
const imageUrl = (id) => `${imageBase}${id}`;
const Arrow = ({ name = 'arrow_forward' }) => <span className="material-symbols-outlined">{name}</span>;

export default function Home() {
  const [submitted, setSubmitted] = useState(false);
  return <main className="exact-home">
    <section className="exact-hero"><div className="exact-organic-bg" /><div className="exact-container exact-hero-grid"><div className="exact-hero-copy"><span className="exact-pill"><i /> The Botanical Selection</span><h1>Naturally good.<br /><em>Thoughtfully</em><br />selected.</h1><p>Discover a world of carefully selected foods, flavours, and everyday goodness from Frudex. Cultivated across authentic terroirs for those who relish genuine culinary grace.</p><div className="exact-actions"><a className="exact-lime-button" href="#products">Explore Our Products <Arrow name="east" /></a><a className="exact-ghost-button" href="#about">Discover Frudex <Arrow name="south" /></a></div></div><div className="exact-hero-image"><img alt="Gourmet still life of Frudex dates, nuts and pistachios" src="/images/home_hero.png" /><div className="exact-image-caption"><div><span className="exact-label">Harvest Dossier 01</span><strong>Medjool Date &amp; Pistachio Reserve</strong></div><span className="exact-icon">spa</span></div></div><div className="exact-ribbon"><span>● Est. Select Foods</span><span>● Premium FMCG Excellence</span><span>● Sourced Across 18 Origin Terroirs</span><span>● Hermetic Flavour Retention</span></div></div></section>
    <section className="exact-light-section" id="about"><div className="exact-container exact-about-grid"><div><span className="exact-label exact-green">Philosophy &amp; Provenance</span><h2>Goodness, selected<br /><em>with purpose.</em></h2><p className="exact-lead">Frudex was conceived at the intersection of agricultural respect and culinary pleasure. We believe that everyday food should elevate ordinary routines into sensory milestones.</p><p>Rather than industrial consolidation, our procurement operates on micro-climates, seasonal cycles, and patient sorting. Every single date, nut cluster, and confection is treated with unhurried discernment, preserving authentic oils, delicate sugars, and structural crunch.</p><div className="exact-pillars">{[['01 / Quality', 'Stringent multi-stage calibration of size, moisture, and tasting profiles.'], ['02 / Authenticity', 'Traceable origin partnerships with multigenerational orchard growers.'], ['03 / Thoughtful Selection', 'Curated for palate equilibrium, balanced textures, and rich natural vitality.'], ['04 / Customer Trust', 'Airtight protective packaging preserving freshness from grove to table.']].map(([title, text]) => <div key={title}><span className="exact-label exact-green">{title}</span><p>{text}</p></div>)}</div></div><div className="exact-about-image"><img alt="Premium dates and pistachios on slate" src="/images/home_page.png" /><div><strong>The Curated Harvest</strong></div></div></div></section>
    <section className="exact-products" id="products"><div className="exact-container"><div className="exact-section-heading"><span className="exact-label exact-green">● &nbsp;Comprehensive FMCG Range</span><h2>Our products</h2><p>A carefully selected world of flavours, goodness, and everyday indulgence. Frudex offers more than just dry fruits—delve into eleven distinct harvest chapters.</p></div><div className="exact-product-grid">{products.map(([number, origin, title, text, image]) => <article key={title}><div className="exact-card-meta"><span>{number}</span><span>{origin}</span></div><img alt={title} src={imageUrl(image)} /><h3>{title}</h3><p>{text}</p><a href="#contact">Explore {title} <Arrow /></a></article>)}</div><div className="exact-secondary-grid">{secondaryProducts.map((title, index) => <article key={title}><span className="exact-label exact-green">0{index + 5} / {['Indulgence', 'Aroma', 'Everyday', 'Elixirs'][index]}</span><h3>{title}</h3><p>Thoughtfully selected flavour, texture, and natural character.</p><a href="#contact">Explore <Arrow name="north_east" /></a></article>)}</div><div className="exact-discover-grid">{['IMPORTED', 'MUNCHIES', 'GIFT BOX & HAMPERS'].map((title, index) => <article className={index === 2 ? 'exact-dark-card' : ''} key={title}><span className="exact-label">0{index + 9} / {index === 2 ? 'Bespoke' : 'Terroir'}</span><h3>{title}</h3><p>Discover a carefully selected collection designed for modern tables, travel, and celebration.</p><a href="#contact">Explore {title} <Arrow /></a></article>)}</div></div></section>
    <section className="exact-quality"><div className="exact-container"><div className="exact-section-heading exact-centered"><span className="exact-label exact-green">Our Quality Standard</span><h2>Why Frudex</h2><p>An unwavering dedication to natural purity, aesthetic integrity, and multi-generational harvesting wisdom.</p></div><div className="exact-quality-grid">{[['spa', 'Carefully Selected', 'Quality products chosen with obsessive attention to harvest timing, soil health, and pod sizing.'], ['edit_note', 'Naturally Good', 'Wholesome goodness inspired by nature, free from unnecessary artificial interventions or shortcuts.'], ['verified_user', 'Quality You Can Trust', 'Consistency and care in every pack. Fully certified laboratory standards and rigorous sensory trials.'], ['wb_sunny', 'Made for Every Moment', 'Thoughtfully selected products for everyday enjoyment, celebration, wellness, and hospitality.']].map(([icon, title, text]) => <article key={title}><span className="exact-feature-icon material-symbols-outlined">{icon}</span><span className="exact-label exact-green">Feature</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="exact-journey"><div className="exact-container"><div className="exact-section-heading"><span className="exact-label">The Quality Journey</span><h2>From selection to<br /><em>your everyday.</em></h2><p>A four-stage continuum safeguarding nutritional integrity, pristine flavour profiles, and tactile pleasure.</p></div><div className="exact-journey-grid">{[['01', 'Selected', 'Handpicked grades calibrated for optimal ripeness, uniform caliber, and peak harvest seasonality.', 'Origin Terroir'], ['02', 'Quality Check', 'Multi-stage inspection, optical sorting, and internal lab sensory validation protocols.', 'Lab Standards'], ['03', 'Carefully Packed', 'Hermetic seal barriers preserving volatile oils, aromas, and crispness without preservatives.', 'Freshness Lock'], ['04', 'Ready to Enjoy', 'Wholesome nourishment and refined gastronomy delivered seamlessly to discerning kitchens.', 'Table Grace']].map(([number, title, text, phase]) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{text}</p><span className="exact-label">Phase · {phase}</span></article>)}</div></div></section>
    <section className="exact-packaging"><div className="exact-container exact-packaging-grid"><div><span className="exact-label exact-green">Aesthetic Integrity</span><h2>Goodness worth<br /><em>sharing.</em></h2><p className="exact-lead">Our packaging philosophy mirrors our culinary standards: tactile luxury, understated forest greens, and materials that preserve nature&apos;s bounty with dignity.</p><p>From FSC-certified matte cardstock to double-walled gold-embossed presentation tins, every container is designed to dwell gracefully on coffee tables, executive desks, and banquet spreads.</p><ul><li>Hermetic Oxygen Barriers for Peak Crispness</li><li>Bespoke Gold Foil Calligraphy &amp; Minimal Typography</li><li>Reusable Rigid Keepsake Gift Cases</li></ul></div><div className="exact-packaging-cards"><article><img alt="Frudex signature reserve pouch" src="/images/Pouch.png" /><h3>Signature Reserve Pouch</h3><p>Multi-barrier film with matte velvet touch</p></article><article><img alt="Frudex prestige celebration box" src="/images/Gift_box.png" /><h3>Prestige Celebration Box</h3><p>Rigid keepsake box with satin pull-ribbon</p></article></div></div></section>
    <section className="exact-lifestyle"><div className="exact-container"><div className="exact-section-heading"><span className="exact-label exact-green">Daily Rituals</span><h2>A little goodness,<br /><em>every day.</em></h2><p>From solitary morning focus to exuberant festive banquets, discover how Frudex complements modern culinary cadences.</p></div><div className="exact-moments-grid">{moments.map(([label, title, image]) => <article key={title}><img alt={title} src={image} /><div><span className="exact-label">{label}</span><h3>{title}</h3><p>Thoughtful goodness for the rhythm of modern life.</p></div></article>)}</div></div></section>
    <section className="exact-statement"><div className="exact-rings" /><span className="exact-label">The Botanical Horizon</span><h2>More to discover.<br /><em>More to enjoy.</em></h2><p>From everyday essentials to thoughtful indulgences, Frudex brings together a diverse selection of products made for every moment.</p><a className="exact-lime-button" href="#contact">Connect With Our Team <Arrow name="south" /></a></section>
    <section className="exact-contact" id="contact"><div className="exact-container exact-contact-grid"><div><span className="exact-label exact-green">Direct Channel</span><h2>Let&apos;s connect.</h2><p className="exact-lead">Have a question, business enquiry or want to know more about Frudex? We&apos;d love to hear from you.</p><div className="exact-contact-copy"><p><strong>Head Office &amp; Reserve Center</strong><br />Frudex Global FMCG Agri-Ventures<br />Botanical Quality Labs, Suites 401-404</p><p><strong>Business &amp; Distribution Inquiries</strong><br /><a href="mailto:partnerships@frudex.com">partnerships@frudex.com</a></p><p><strong>Trade Desk</strong><br />+1 (800) 482-3783 / +44 20 7946 0912</p></div></div><form className="exact-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><h3>Submit a Corporate Enquiry</h3><div className="exact-form-row"><label>Full Name<input required placeholder="e.g. Lord Alistair Vance" type="text" /></label><label>Corporate / Personal Email<input required placeholder="name@organization.com" type="email" /></label></div><div className="exact-form-row"><label>Phone Number<input placeholder="+44 20 ..." type="tel" /></label><label>Enquiry Type<select defaultValue="retail"><option value="retail">Retail Distribution &amp; Stockist</option><option value="gifting">Corporate &amp; Institutional Gifting</option><option value="harvest">Direct Harvest Procurement</option></select></label></div><label>Your Message<textarea required placeholder="Please outline your inquiry, estimated quantities, or regional requirements..." rows="4" /></label><button className="exact-lime-button" type="submit">Send Enquiry <Arrow name="send" /></button>{submitted && <p className="exact-success"><Arrow name="check_circle" /> Thank you. Your message has been routed to our corporate relations directorate.</p>}</form></div></section>
  </main>;
}
