import { useState } from 'react';
import { Link } from 'react-router-dom';
import { productImages } from '../../data/productDetails';
import HeroLinework from '../../components/common/HeroLinework';

const imageBase = 'https://lh3.googleusercontent.com/aida-public/';
const ribbonItems = ['Trusted Quality Foods', 'Premium Quality', 'Sourced From 18 Countries', 'Stays Fresh Longer'];
const products = [
  ['01 / Reserve', 'Origin: Jordan Valley', 'DATES', 'Rich, sweet dates with a natural caramel taste — straight from the palm.', '/images/Dates.png', 'dates'],
  ['02 / Crunch', 'Origin: Multi-Region', 'NUTS', 'Golden roasted almonds, cashews, pistachios, and walnuts — crunchy and healthy.', '/images/Nuts.png', 'nuts'],
  ['03 / Essence', 'Origin: Sun-Dried', 'DRY FRUITS', 'Naturally sweet, sun-dried fruits packed with flavour.', '/images/Dry_Fruits.png', 'dry-fruits'],
  ['04 / Vitality', 'Origin: Raw & Roasted', 'SEEDS', 'Small seeds, big goodness — a healthy addition to your daily diet.', '/images/Seeds.png', 'seeds'],
];
const secondaryProducts = [
  ['CHOCOLATES', 'chocolates', productImages.chocolate],
  ['SPICES', 'spices', productImages.spices],
  ['SNACKS', 'snacks', productImages.snacks],
  ['BEVERAGES', 'beverages', productImages.beverages],
];
const discoverProducts = [
  ['IMPORTED', 'imported-specialties', productImages.imported],
  ['MUNCHIES', 'munchies', productImages.munchies],
  ['GIFT BOX & HAMPERS', 'gift-boxes-hampers', productImages.gifting],
];
const moments = [
  ['Morning', 'Breakfast & Energy', '/images/breakfast.png'],
  ['Work Break', 'Stay Focused All Day', '/images/work.png'],
  ['Evenings', 'Family Time & Celebrations', '/images/family.png'],
  ['Gifting', 'Perfect for Festivals & Sharing', '/images/Gift.png'],
  ['Hosting Guests', 'Great for Entertaining', '/images/elegent.png'],
  ['On the Go', 'Easy Snacking Anywhere', '/images/travel.png'],
];
const imageUrl = (id) => `${imageBase}${id}`;
const Arrow = ({ name = 'arrow_forward' }) => <span className="material-symbols-outlined">{name}</span>;

export default function Home() {
  const [submitted, setSubmitted] = useState(false);
  return <main className="exact-home">
    <section className="exact-hero"><div className="exact-organic-bg" /><HeroLinework /><div className="exact-container exact-hero-grid"><div className="exact-hero-copy"><span className="exact-pill"><i /> Our Handpicked Selection</span><h1>Naturally good.<br /><em>Thoughtfully</em><br />selected.</h1><p>Discover tasty, high-quality dry fruits, nuts, and everyday treats from Frudex. Every product is chosen carefully for real taste and quality.</p><div className="exact-actions"><a className="exact-lime-button" href="#products">Explore Our Products <Arrow name="east" /></a><a className="exact-ghost-button" href="#about">Discover Frudex <Arrow name="south" /></a></div></div><div className="exact-hero-image"><img alt="Gourmet still life of Frudex dates, nuts and pistachios" src="/images/home_hero.png" /><div className="exact-image-caption"><div><span className="exact-label">Featured Product</span></div><span className="exact-icon">spa</span></div></div><div className="exact-ribbon"><div className="exact-ribbon-track">{ribbonItems.map((item) => <span key={item}>● {item}</span>)}</div><div aria-hidden="true" className="exact-ribbon-track">{ribbonItems.map((item) => <span key={`dup-${item}`}>● {item}</span>)}</div></div></div></section>
    <section className="exact-light-section" id="about"><div className="exact-container exact-about-grid"><div><span className="exact-label exact-green">Our Story</span><h2>Good food,<br /><em>chosen with care.</em></h2><p className="exact-lead">Frudex started with one simple idea — good food should bring joy to everyday life.</p><p>We don&apos;t rush. Instead of buying in bulk from anywhere, we choose our dates, nuts, and sweets carefully by season and region. Every batch is checked by hand to keep its natural taste, freshness, and crunch.</p><div className="exact-pillars">{[['01 / Quality', 'Every batch is checked for size, freshness, and taste.'], ['02 / Authenticity', 'We work directly with trusted farmers we know by name.'], ['03 / Thoughtful Selection', 'Picked for great taste, texture, and natural goodness.'], ['04 / Customer Trust', 'Sealed packaging keeps everything fresh from farm to your home.']].map(([title, text]) => <div key={title}><span className="exact-label exact-green">{title}</span><p>{text}</p></div>)}</div></div><div className="exact-about-image"><img alt="Premium dates and pistachios on slate" src="/images/home_page.png" /><div><strong>Our Selection</strong></div></div></div></section>
    <section className="exact-light-section" id="who-we-are"><div className="exact-container exact-about-grid"><div className="exact-about-image"><img alt="Frudex team preparing curated dry fruit selections" src="/images/About_page.png" /><div></div></div><div><span className="exact-label exact-green">Who We Are</span><h2>The people<br /><em>behind Frudex.</em></h2><p className="exact-lead">Frudex is based in Koduvally, Kerala, where we work hard every day to bring you honest, good-quality dry fruits, nuts, and everyday treats.</p><p>Every order is handpicked, inspected, and packed with genuine care before it reaches you. When you buy from Frudex, you&apos;re choosing a business that truly cares about the quality on your table.</p><div className="exact-pillars">{[['Family-Run', 'Started and run by people who care about good food.'], ['Kerala-Based', 'Proudly based in Koduvally, serving customers everywhere.'], ['Hands-On', 'We personally check every batch before it ships.'], ['Customer-First', 'Your satisfaction is always our top priority.']].map(([title, text]) => <div key={title}><span className="exact-label exact-green">{title}</span><p>{text}</p></div>)}</div></div></div></section>
    <section className="exact-products" id="products"><div className="exact-container"><div className="exact-section-heading"><span className="exact-label exact-green">● &nbsp;Our Product Range</span><h2>Our products</h2><p>More than just dry fruits — explore all 11 categories of Frudex products.</p></div><div className="exact-product-grid">{products.map(([number, origin, title, text, image, slug]) => <article key={title}><div className="exact-card-meta"><span>{number}</span><span>{origin}</span></div><img alt={title} src={(image)} /><h3>{title}</h3><p>{text}</p><Link to={`/products/${slug}`}>Explore {title} <Arrow /></Link></article>)}</div><div className="exact-secondary-grid">{secondaryProducts.map(([title, slug, image], index) => <article key={title}><span className="exact-label exact-green">0{index + 5} / {['Indulgence', 'Aroma', 'Everyday', 'Elixirs'][index]}</span><img alt={title} src={image} /><h3>{title}</h3><p>Handpicked for great taste and quality.</p><Link to={`/products/${slug}`}>Explore <Arrow name="north_east" /></Link></article>)}</div><div className="exact-discover-grid">{discoverProducts.map(([title, slug, image], index) => <article className={index === 2 ? 'exact-dark-card' : ''} key={title}><span className="exact-label">0{index + 9} / {index === 2 ? 'Bespoke' : 'Terroir'}</span>{image && <img alt={title} src={image} />}<h3>{title}</h3><p>A handpicked collection, great for gifting, travel, and celebrations.</p><Link to={`/products/${slug}`}>Explore {title} <Arrow /></Link></article>)}</div></div></section>
    <section className="exact-quality"><div className="exact-container"><div className="exact-section-heading exact-centered"><span className="exact-label exact-green">Our Quality Standard</span><h2>Why Frudex</h2><p>We focus on pure, natural food and time-tested sourcing methods.</p></div><div className="exact-quality-grid">{[['spa', 'Carefully Selected', 'We pick every product carefully, paying attention to freshness, quality, and size.'], ['edit_note', 'Naturally Good', 'Natural and wholesome, with no unnecessary additives or shortcuts.'], ['verified_user', 'Quality You Can Trust', 'Every pack is tested and certified, so you always get the same great quality.'], ['wb_sunny', 'Made for Every Moment', 'Great for everyday snacking, celebrations, gifting, and more.']].map(([icon, title, text]) => <article key={title}><span className="exact-feature-icon material-symbols-outlined">{icon}</span><span className="exact-label exact-green">Feature</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="exact-journey"><div className="exact-container"><div className="exact-section-heading"><span className="exact-label">The Quality Journey</span><h2>From selection to<br /><em>your everyday.</em></h2><p>Four simple steps that keep every product fresh, tasty, and healthy.</p></div><div className="exact-journey-grid">{[['01', 'Selected', 'We handpick each item at the right time for the best ripeness and size.', 'Farm Origin'], ['02', 'Quality Check', 'Every batch is checked and tested for quality.', 'Lab Tested'], ['03', 'Carefully Packed', 'Sealed packaging keeps everything fresh and crunchy, with no preservatives.', 'Stays Fresh'], ['04', 'Ready to Enjoy', 'Delivered fresh and ready for you to enjoy.', 'Ready to Eat']].map(([number, title, text, phase]) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{text}</p><span className="exact-label">Phase · {phase}</span></article>)}</div></div></section>
    <section className="exact-packaging"><div className="exact-container exact-packaging-grid"><div><span className="exact-label exact-green">Our Packaging</span><h2>Goodness worth<br /><em>sharing.</em></h2><p className="exact-lead">We pack our products with the same care we put into choosing them — quality materials that keep everything fresh and look great too.</p><p>From eco-friendly cardboard to elegant gift tins, every pack looks great anywhere — at home, at work, or as a gift.</p><ul><li>Sealed Packs Keep Food Fresh &amp; Crunchy</li><li>Elegant, Simple Design</li><li>Sturdy Boxes You Can Reuse</li></ul></div><div className="exact-packaging-cards"><article><img alt="Frudex signature reserve pouch" src="/images/Pouch.png" /><h3>Signature Reserve Pouch</h3><p>A soft-touch pouch that keeps food fresh</p></article><article><img alt="Frudex prestige celebration box" src="/images/Gift_box.png" /><h3>Prestige Celebration Box</h3><p>A sturdy gift box with a ribbon pull, great for gifting</p></article></div></div></section>
    <section className="exact-lifestyle"><div className="exact-container"><div className="exact-section-heading"><span className="exact-label exact-green">Daily Rituals</span><h2>A little goodness,<br /><em>every day.</em></h2><p>From busy mornings to festive celebrations, Frudex fits every part of your day.</p></div><div className="exact-moments-grid">{moments.map(([label, title, image]) => <article key={title}><img alt={title} src={image} /><div><span className="exact-label">{label}</span><h3>{title}</h3><p>Simple, healthy goodness for everyday life.</p></div></article>)}</div></div></section>
    <section className="exact-statement"><div className="exact-rings" /><span className="exact-label">Explore More</span><h2>More to discover.<br /><em>More to enjoy.</em></h2><p>From everyday snacks to special treats, Frudex has something for every moment.</p><a className="exact-lime-button" href="#contact">Connect With Our Team <Arrow name="south" /></a></section>
    <section className="exact-contact" id="contact"><div className="exact-container exact-contact-grid"><div><span className="exact-label exact-green">Get in Touch</span><h2>Let&apos;s connect.</h2><p className="exact-lead">Have a question, business enquiry or want to know more about Frudex? We&apos;d love to hear from you.</p><div className="exact-contact-copy"><p><strong>Head Office</strong><br />N.I.T Road, Chundappuram<br />Koduvally, Kozhikode 673572, Kerala, India</p><p><strong>Business &amp; Distribution Inquiries</strong><br /><a href="mailto:frudexdryfruits@gmail.com">frudexdryfruits@gmail.com</a></p><p><strong>Trade Desk</strong><br /><a href="tel:+918129555591">+91 81295 55591</a></p></div></div><form className="exact-form" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><h3>Send Us a Message</h3><div className="exact-form-row"><label>Full Name<input name="Full Name" required placeholder="e.g. Ahmed Khan" type="text" /></label><label>Email Address<input name="Email" required placeholder="you@example.com" type="email" /></label></div><div className="exact-form-row"><label>Phone Number<input name="Phone" placeholder="+91 81295 55591" type="tel" /></label><label>Enquiry Type<select defaultValue="retail" name="Enquiry Type"><option value="retail">Retail / Stockist</option><option value="gifting">Corporate Gifting</option><option value="bulk">Bulk Order</option></select></label></div><label>Your Message<textarea name="Message" required placeholder="Tell us what you need — product, quantity, and delivery location..." rows="4" /></label><button className="exact-lime-button" type="submit">Send Enquiry <Arrow name="send" /></button>{submitted && <p className="exact-success"><Arrow name="check_circle" /> Thank you! We&apos;ve received your message and will get back to you soon.</p>}</form></div></section>
  </main>;
}
