import { useState } from 'react';
import { Link } from 'react-router-dom';
import { productDetails, productImages as images } from '../../data/productDetails';
import HeroLinework from '../../components/common/HeroLinework';

const cornerstones = productDetails.filter((p) => p.section === 'cornerstone').map((p) => [p.number, p.badge, p.title, p.quote, p.imageKey, p.description, p.location, p.slug, p.specs]);
const pantry = productDetails.filter((p) => p.section === 'pantry').map((p) => [p.number, p.title, p.imageKey, p.quote, p.description, p.slug]);
const discover = productDetails.filter((p) => p.section === 'discover').map((p) => [p.number, p.title, p.imageKey, p.quote, p.description, p.slug]);
function Icon({ children }) { return <span className="material-symbols-outlined">{children}</span>; }
function Label({ children, light = false }) { return <span className={`products-label ${light ? 'products-label-light' : ''}`}>{children}</span>; }
function ProductCard({ item }) { const [number, badge, title, quote, key, text, location, slug, specs] = item; return <article className="cornerstone-card"><div><div className="card-top"><Label>{number}</Label><span className="products-badge">{badge}</span></div><h3>{title}</h3><p className="products-quote">{quote}</p><div className="product-image"><img alt={title} src={images[key]} /><span className="image-chip">{location}</span></div><p className="product-description">{text}</p><div className="spec-grid"><span><b>Varieties</b>{specs.cultivars}</span><span><b>Tasting Notes</b>{specs.tastingNotes}</span><span><b>Specification</b>{specs.specification}</span></div></div><Link to={`/products/${slug}`}>View Details <Icon>arrow_forward</Icon></Link></article>; }
export default function Products() { const [submitted, setSubmitted] = useState(false); return <main className="products-reference">
  <section className="products-hero"><div className="products-hero-glow" /><HeroLinework /><div className="products-container products-hero-grid"><div><span className="products-pill"><i /> Our Full Product Range</span><h1>Explore All Our Products.</h1><p>From dates and nuts to spices and gift boxes — explore all 11 categories of Frudex products.</p><div className="products-meta"><span><Icon>verified</Icon>11 Categories</span><span><Icon>eco</Icon>Traceable Sourcing</span><span><Icon>hotel_class</Icon>Premium Quality</span></div></div><div className="products-hero-image"><img alt="Curated gourmet dates, nuts and pistachios" src="/images/Products_page.png" /><div><Label light>Product Specification</Label><span>100% Traceable</span></div></div><nav className="products-filter"><a className="active" href="#cornerstone-selections">All Categories (11)</a><a href="#cornerstone-selections">Featured Selections</a><a href="#secondary-suite">Pantry &amp; Spices</a><a href="#discover-suite">Confections &amp; Munchies</a><a href="#bespoke-gifting">Bespoke Gifting</a></nav></div></section>
  <section className="products-section" id="cornerstone-selections"><div className="products-container"><div className="products-heading"><div><Label>Featured Categories</Label><h2>Our Main Categories</h2><p>More than just dried fruits — each category is chosen for great taste and quality.</p></div><Label>Categories 01 — 04</Label></div><div className="cornerstone-grid">{cornerstones.map((item) => <ProductCard item={item} key={item[2]} />)}</div></div></section>
  <section className="products-secondary" id="secondary-suite"><div className="products-container"><div className="products-centered"><Label>Pantry Favourites</Label><h2>Our Pantry Range</h2><p>Everyday favourites — spices, chocolate, and crunchy snacks.</p></div><div className="pantry-grid">{pantry.map(([number, title, key, quote, text, slug]) => <article key={title}><div><div className="card-top"><Label>{number}</Label><Icon>{title === 'Chocolates' ? 'cookie' : title === 'Spices' ? 'psychiatry' : title === 'Snacks' ? 'bakery_dining' : 'local_cafe'}</Icon></div><h3>{title}</h3><p className="products-quote">{quote}</p><img alt={title} src={images[key]} /><p>{text}</p></div><Link to={`/products/${slug}`}>View Details <Icon>arrow_forward</Icon></Link></article>)}</div></div></section>
  <section className="products-section" id="discover-suite"><div className="products-container"><div className="products-heading"><div><Label>Categories 09 — 11</Label><h2>Specialty Items &amp; Gifting</h2></div><p>Unique imported treats and beautifully presented gift boxes for any occasion.</p></div><div className="discover-grid">{discover.map(([number, title, key, quote, text, slug], index) => <article className={index === 2 ? 'discover-feature' : ''} id={index === 2 ? 'bespoke-gifting' : undefined} key={title}><div><div className="card-top"><Label light={index === 2}>{number}</Label><span>{index === 2 ? 'Corporate Exclusive' : 'Global Sourcing'}</span></div><h3>{title}</h3><p className="products-quote">{quote}</p><img alt={title} src={images[key]} /><p>{text}</p></div><Link to={`/products/${slug}`}>Explore Collection <Icon>arrow_forward</Icon></Link></article>)}</div></div></section>
  <section className="products-packaging"><div className="products-container packaging-grid"><div className="packaging-visual"><img alt="Frudex forest green packaging" src={images.pack} /><div><span><Icon>shield</Icon> Nitrogen Sealed</span><span><Icon>nature</Icon> 100% Recyclable Board</span></div></div><div><Label>Our Packaging</Label><h2>Packed to Stay Fresh.</h2><p className="products-lead">Regular plastic doesn&apos;t keep food fresh for long. Every Frudex pack is designed to block air, light, and moisture, so your food stays fresh longer.</p><div className="standards-grid">{[['air', 'Multi-Layer Protection'], ['light_mode', 'Blocks Sunlight'], ['filter_drama', 'Nitrogen Sealed'], ['recycling', 'Plastic-Free Packaging']].map(([icon, title]) => <article key={title}><Icon>{icon}</Icon><h3>{title}</h3><p>Keeps your food fresh, tasty, and crunchy for longer.</p></article>)}</div></div></div></section>
  <section className="products-banner"><div className="products-container"><div><Label light>Business Partnerships</Label><h3>Partner With Frudex for Bulk Supply.</h3><p>We supply hotels, restaurants, offices, and shops in 18 countries.</p></div><div><button onClick={() => window.alert('Preparing the FRUDEX Master Product Catalog.')}> <Icon>download</Icon> Master Catalog (PDF, 24MB)</button><a href="#institutional-inquiry">Contact Our Team <Icon>arrow_forward</Icon></a></div></div></section>
  <section className="products-enquiry" id="institutional-inquiry"><div className="enquiry-card"><div className="products-centered"><Label>Get in Touch</Label><h2>Let&apos;s Connect</h2><p>Talk to our team about bulk orders, product samples, or custom branding.</p></div><form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><div className="enquiry-fields"><label>Full Name *<input name="Full Name" required placeholder="e.g. Ahmed Khan" /></label><label>Email Address *<input name="Corporate Email" required placeholder="you@example.com" type="email" /></label><label>Phone Number *<input name="Phone" required placeholder="+91 81295 55591" type="tel" /></label><label>Enquiry Type *<select defaultValue="Bulk Order" name="Inquiry Domain"><option>Bulk Order</option><option>Hospitality / Hotels</option><option>Corporate Gifting</option><option>Private Label</option></select></label></div><label>Order Details *<textarea name="Allocation Scope / Details" required placeholder="Tell us what you need — product, quantity, and delivery location..." rows="4" /></label><div className="enquiry-submit"><span><Icon>lock</Icon> Your information is kept private and confidential.</span><button type="submit">Send Enquiry <Icon>send</Icon></button></div>{submitted && <p className="products-success"><Icon>task_alt</Icon><strong>Message Sent!</strong> We&apos;ll review your request and get back to you soon.</p>}</form></div></section>
 </main>; }
