import { useState } from 'react';

const images = {
  hero: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC7ziNJM5ib7pq5tN66P-3fZfrgzacGssXxKm3yHDDYdBsRiFVg3wk45X3iop0T0O2wcrykIbApN5G2jOM6mlfqm_2NpuT7dWlc3sOA8xiHbDHjzWIbYfwnFhbzeFkc4fa916kfwMOisEawVLVX2NBEsEGXBfFnJPWByD07XKWox8oRl4BFL5dH3JisfPmdbzXUO7xYaDlrg7rjdhVyB42nCCUgQzQXSDI3nT669kwYB53iVmIYL1AXWw',
  dates: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDhUDbOFLHNCa7MTppfEgFaciip1e-Ua9h-C3VDtqLlmWuDRp32H-MefGMCKDvvRR_Mt4V2B6otF0-1fwNV1XJzIq7gWOITCdCXuVDOxi-zRxuaSsgIoeztu-8yvSbgqsctBW3R6wom1sDpLMIO4AerS9ROhd5B1A8Va5WKOS8mXgo_V-GbYH185YHS0GcUxRF8nlyXni0ZI-xR-iv2DUiNMlsh0DCUQ_adioEoUw8VdZuvsRD_U-zoTg',
  nuts: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDWdt55TOrPXFTg6z2tYVHefr6S_exn08YhJTvDMIxMh_y43p0H2hfk_rUe0UMo-u7lWbhbRELzZR3JMibcCMIJptgi8HB9I9nvEmzYx3j7ac94tD2UaWh2fCvtc6hJfKYuAmF5Pt8KkxgxbTdpzw2Hhb9k7sQbQQY4k0cqbmHaiQYKsTJxUPDeWfltPGSddbXXUrG3AJ2Dj5QMsRTS-cXwkl7KTzPoDc1fFOlFAy7qOwuzaY4V8ULm7w',
  dry: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDXMZy1CiAtHwuWj7np5k3r7SBzZz1fT-36mqsaUowXXV64-IEkrmmdmPI0W7tsbRufYDT1mCUGvRlXNpAdvE8yvX2_0J6YvDOFJJ32ftwEcGnUwVuQy3FKfpHETz3vKjLR9zM3KrkPZ3vi-bH3jDYXZGSSF2DaKsxEgLWJrXHqNMnRLl3fLjkfJSUwlbqc6ir2M3XdX7Ddfp6tssh5a1lZBbec1vd27Sq18Ckm-KBQJfIU0phDkqC_NA',
  seeds: 'https://lh3.googleusercontent.com/aida-public/AB6AXuByaCzxDWFxoTmiH9Mh95XbsE-xCV5hN_rwoJAe4-Bx9yJ2J4K955uJ-hLUrKdjW41aCw5FXvtRCGNsOmKg9DP9UJd-JFWViBy2dlLYv__tuGkrqktzR-hOR4Jjms2Y7EbutRVsOZOXjrDqzjqSz9jLIYLcJ2GZRhav4QA4lEzOm4IU3QQcEaAsmMaVCS0nfsXcBmW86ooyWv3oJxUBBpkgsphGbF4H5SU3ggozMGDBgoOk9BvaJbqdBg',
  chocolate: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBVuFVjjMz9oXBGfI8iNCXWfbNmiZnlMVVI_joeEE4lpBu3HVUNVfqqnJ9rIQcXQ8SXcsuXBGW203iIHGXAAl2fbhHBeNfIe5xZG5Di9ABhLipmlbQSF5qkNBHVynyXeu-P7C5wbjDQmQAZyZi0sWNbca0_YtmQx1BKUFM3vIPBBqpP2Z7v9ytU29qzzCWemj2GDj79u92-s1bBhy-VCYOh4NGnQWK4CWFYXLVUwRUDR75rWXKYkC4Y6g',
  spices: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBET0QbRzvVljPdGoPfHfJeNgPFWwt-8KKOLQMocyuphY6pq6SPJXyu2FYD7ozCaOKI00JJwvZvDBcREdHD3A4OrVz6UKN10y26j0fm4Mojfo-hwCqFVpZLpfAhiOGkpOpNlc7uSp_S1PxZGCQNSYooK4UzdQJiyQki6xyKt_L2ig_EsFr9XU_mBFdbHD6j6o6wMMTolQNZMzVztpMvppy3GAO2ZU5Dffb95wUzbsLiSs6C_ziQQu-Neg',
  snacks: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAcScZu90gAFoU_UNVeM36JfEa87xZdPZqCJ9t-3WggnD-pbzs0oiTcNP1XY_Q3dxOE7_KovMo3Ond03DndIkGX2_RRPLLHUPgiqOgNzQSVZQKa56uarZ6W1FOwPs5YXlXAUJJ2cuGh9Mj4lBOOfYV3ZjTYtqLZQxVXYrLsBodUxNfQ8A4zeyh1szOfen48B3CSTvvEPbySxcdL6DYXjb5vOeDhxVQJq25rHmDx4EpcUoPx2KJKevv0lw',
  beverages: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCPX7Ira6NHMFC3qMUc-Hwa7TRHw8wvXEZu7qzPNKwG9CM7QtamwyFZAJki9SEPVM6LmJ1cPYSe7tUtEEHykfH0214DMKJ9N5q4ykzc1lGb0htvhJpSV0ZpaFIG8Ruk03VC5B8WtHOuzp3ZG2DkkmdXO3W0tiND9Wf_ugRKGeBGE3UQj-RJxySjWStdDDRRfeEL9m175UCM5UrwHoBPbD0zRxsh435vcIh9LE-t9acnxMoFqzkZKu9o-g',
  imported: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDVkB9sqUwwTcC8PgMKxI2Uqwa8yqGBxs3u4IFawyuam6kPSBcMUP36PUpkUlvSuR4HblswWbzn_qYvVrKo7R5jxspsnhsaayXZvWKnH5_dPTERvDgyE-xnYzOavXGLnAXdZW3D50ySs_kZh6BcYRzQKS5IJgaMldDajhO5l4veP8d35WLrYyKaugnb93sYUsQzfcug4bsSfyUsBu3BZeqRuQWwaKGMX7Tm6_qHNCjrmFx47ONIjPifXg',
  munchies: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9SRNODOK9G5pYdVdpEsDwaJQxLLUAS3PYbyv9cbTQuPPxa3o6VhsS5aP7KEo7hfyfDTjY097bmQWdRf0FEccojdbCB3Z_lmDi7UsTKEoR0qb3TRBp1yHezf6R2zRAt9iY7sJzViaPtoF3qvaGTrPYUqAjmNQ66rXzSNdEFVrASXb-qZdWsZzcBhvcaFqOY6y2SjgeBnACv_zoRxkVfbI92AIO8PY5wIZ2vmoZCXNwBc3V-0fKkXGlxw',
  gifting: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAV0YpJ_LntZFot3fbMcB7vp0ot1u5nfSNO58Z8kk9XXnXACCA03enz1YH8ovy2Mf9VlKbm7V8bSE3Ckngqaqvnqo6waX8CRTc_tc_UAYiTKx6iBufGe0J39-Jmcprd0NTmmy1yLZBsddPiKHAC5AATahaLDml_2mO-PA5Fp8L-78q3JbYirj1ang5FNbtb_Dah-qt1rbpV75UTXTE061finhl8INLBqyjQU0Px3ziYmgD8B2v7WDHCuQ',
  pack: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBtFXbf13qemonNQHwk3D3j9sAeNhipU9njqwEvJwYhLNawvFztXb95EIRhxnrVeGfdIjv2KcUzca9M_DrUe8Vk4pwT3nSUPWFrYTM4DIhMVk8XzI1t6YFL4Fz0DpFLrOy5gZOPq2ARJDMq3OcuNGe0pk1NUbwVatO0WXTlKDhcsjqLbCzwc7XQfIU6Rh9WHwyFP4ZDXRg3_3iGUJN0rNkKjaiktPILJ9hlkcK-KzSsVc_5y_ohh89B8A',
};
const cornerstones = [
  ['01 / Reserve', 'Single-Estate Lot', 'Dates', '“Naturally rich. Naturally delicious.”', 'dates', 'Harvested exclusively from heritage palms across Al-Qassim and the Jordan Rift. Featuring prime Jumbo Medjool, Ajwa of Medina, and taut amber Mabroom cured naturally on the branch without added glucose or thermal alteration.', 'Desert Oases'],
  ['02 / Reserve', 'Highland Terroir', 'Nuts', '“Wholesome crunch, thoughtfully selected.”', 'nuts', 'Selected for natural oil density and sound acoustic crispness. We source cold-cracked Iranian Mamra almonds, Chandler wild mountain walnuts, and whole kernel Gaziantep pistachios untouched by bleach or fumigants.', 'Highland Terroir'],
  ['03 / Reserve', 'Solar Dehydration', 'Dry Fruits', '“Naturally sweet. Beautifully satisfying.”', 'dry', 'Gentle sun-drying preserves the vibrant pectin lattice and authentic fruit sugars. Hand-selected Turkish mountain apricots, Aegean string-dried figs, and cold-region wild cranberries balanced without artificial syrups.', 'Solar Dehydration'],
  ['04 / Reserve', 'Superfood Matrix', 'Seeds', '“Small in size. Big on goodness.”', 'seeds', 'Dense micro-nutritional reserves selected from organic botanical soils. Featuring Styrian hull-less pumpkin seeds, high-mucilage chia, and slow-roasted heirloom sesame.', 'Superfood Matrix'],
];
const pantry = [['05 / Indulgence', 'Chocolates', 'chocolate', '“Little moments of indulgence.”', 'Single-origin 72% Ecuadorian stone-ground cacao paired harmoniously with Medjool paste and fleur de sel flakes.'], ['06 / Terroir', 'Spices', 'spices', '“Flavour that brings every dish alive.”', 'Hand-plucked Kashmiri saffron, bold Malabar green cardamom, and fragrant Ceylon cinnamon bark.'], ['07 / Savoury', 'Snacks', 'snacks', '“Something delicious for every moment.”', 'Vacuum-roasted savoury medleys seasoned lightly with Himalayan salt, Tellicherry pepper, and garden thyme.'], ['08 / Infusion', 'Beverages', 'beverages', '“Refreshingly good, anytime.”', 'Cold-pressed botanical infusions, roasted date-seed tisanes, and sun-dried organic chamomile flower heads.']];
const discover = [['09 / Discover', 'Imported Specialties', 'imported', '“Discover favourites from around the world.”', 'Carefully curated single-origin honey, Andean Physalis berries, and white Persian mulberries sourced in limited seasonal lots.'], ['10 / Crunch', 'Munchies', 'munchies', '“Crunch. Taste. Enjoy.”', 'Crisp oven-baked snacks crafted with ancient grains, slow-toasted pulses, and stone-pressed olive oils.'], ['11 / Masterpiece', 'Bespoke Gift Boxes & Hampers', 'gifting', '“Thoughtfully packed. Made to be shared.”', 'Hand-crafted rigid presentation coffrets, embossed with bespoke corporate insignias and personalized curator calligraphic scrolls.']];
function Icon({ children }) { return <span className="material-symbols-outlined">{children}</span>; }
function Label({ children, light = false }) { return <span className={`products-label ${light ? 'products-label-light' : ''}`}>{children}</span>; }
function ProductCard({ item, onOpen }) { const [number, badge, title, quote, key, text, location] = item; return <article className="cornerstone-card"><div><div className="card-top"><Label>{number}</Label><span className="products-badge">{badge}</span></div><h3>{title}</h3><p className="products-quote">{quote}</p><div className="product-image"><img alt={title} src={images[key]} /><span className="image-chip">{location}</span></div><p className="product-description">{text}</p><div className="spec-grid"><span><b>Cultivars</b>Medjool • Ajwa</span><span><b>Tasting Notes</b>Caramel, Fig, Malt</span><span><b>Specification</b>Super Jumbo A+</span></div></div><button onClick={() => onOpen(`${number} ${title} Dossier`, text)}>View Harvest Dossier <Icon>arrow_forward</Icon></button></article>; }
export default function Products() { const [modal, setModal] = useState(null); const [submitted, setSubmitted] = useState(false); return <main className="products-reference">
  <section className="products-hero"><div className="products-hero-glow" /><div className="products-container products-hero-grid"><div><span className="products-pill"><i /> The Harvest Archive &amp; Master Portfolio</span><h1>An Expansive Archive of Sensory Nourishment.</h1><p>From sun-drenched desert palm groves to mountain walnut orchards and single-estate botanicals. Explore the eleven curated chapters of the Frudex selection.</p><div className="products-meta"><span><Icon>verified</Icon>11 Master Chapters</span><span><Icon>eco</Icon>Single-Estate Provenance</span><span><Icon>hotel_class</Icon>Hospitality Grade Reserve</span></div></div><div className="products-hero-image"><img alt="Curated gourmet dates, nuts and pistachios" src={images.hero} /><div><Label light>Harvest Specification</Label><strong>Est. Selection 2024</strong><span>100% Traceable</span></div></div><nav className="products-filter"><a className="active" href="#cornerstone-harvests">All Chapters (11)</a><a href="#cornerstone-harvests">Featured Harvests</a><a href="#secondary-suite">Pantry &amp; Spices</a><a href="#discover-suite">Confections &amp; Munchies</a><a href="#bespoke-gifting">Bespoke Gifting</a></nav></div></section>
  <section className="products-section" id="cornerstone-harvests"><div className="products-container"><div className="products-heading"><div><Label>Pillar Collections</Label><h2>The Cornerstone Harvests</h2><p>Frudex presents more than dried provisions; we cultivate an archival standard of soil vitality, moisture retention, and culinary density.</p></div><Label>Chapter 01 — 04</Label></div><div className="cornerstone-grid">{cornerstones.map((item) => <ProductCard item={item} key={item[2]} onOpen={setModal} />)}</div></div></section>
  <section className="products-secondary" id="secondary-suite"><div className="products-container"><div className="products-centered"><Label>Botanical &amp; Pantry Mastery</Label><h2>The Curated Pantry Suite</h2><p>Elevating daily gastronomic rituals through rare estate spices, stone-milled single-origin cacao, and pristine vacuum crisps.</p></div><div className="pantry-grid">{pantry.map(([number, title, key, quote, text]) => <article key={title}><div><div className="card-top"><Label>{number}</Label><Icon>{title === 'Chocolates' ? 'cookie' : title === 'Spices' ? 'psychiatry' : title === 'Snacks' ? 'bakery_dining' : 'local_cafe'}</Icon></div><h3>{title}</h3><p className="products-quote">{quote}</p><img alt={title} src={images[key]} /><p>{text}</p></div><Label>Grade 1 Curated Reserve</Label></article>)}</div></div></section>
  <section className="products-section" id="discover-suite"><div className="products-container"><div className="products-heading"><div><Label>Chapters 09 — 11</Label><h2>Specialty Provisions &amp; Bespoke Gifting</h2></div><p>Uncommon culinary rarities complemented by institutional presentation boxes tailored for diplomatic, corporate, and royal recipients.</p></div><div className="discover-grid">{discover.map(([number, title, key, quote, text], index) => <article className={index === 2 ? 'discover-feature' : ''} id={index === 2 ? 'bespoke-gifting' : undefined} key={title}><div><div className="card-top"><Label light={index === 2}>{number}</Label><span>{index === 2 ? 'Corporate Exclusive' : 'Global Sourcing'}</span></div><h3>{title}</h3><p className="products-quote">{quote}</p><img alt={title} src={images[key]} /><p>{text}</p></div><a href={index === 2 ? '#institutional-inquiry' : '#secondary-suite'}>Explore Collection <Icon>arrow_forward</Icon></a></article>)}</div></div></section>
  <section className="products-packaging"><div className="products-container packaging-grid"><div className="packaging-visual"><img alt="Frudex forest green packaging" src={images.pack} /><div><span><Icon>shield</Icon> Hermetic Nitrogen Flush</span><span><Icon>nature</Icon> 100% Recyclable FSC Board</span></div></div><div><Label>Integrity by Design</Label><h2>Goodness Protected by Structural Craftsmanship.</h2><p className="products-lead">Natural produce deteriorates in ordinary commercial plastic. Every Frudex pack is engineered to suspend oxygen decay, block ultraviolet photolysis, and preserve vital oils.</p><div className="standards-grid">{[['air', 'Quad-Layer Barrier'], ['light_mode', 'Total UV Blackout'], ['filter_drama', 'Nitrogen Inoculation'], ['recycling', 'Zero Plastic Presentation']].map(([icon, title]) => <article key={title}><Icon>{icon}</Icon><h3>{title}</h3><p>Designed to preserve freshness, aroma, crunch, and nutritional integrity.</p></article>)}</div></div></div></section>
  <section className="products-banner"><div className="products-container"><div><Label light>Commercial Alliances • Private Reserves</Label><h3>Partner with Frudex for Curated Institutional Supply.</h3><p>We partner with 5-star hospitality groups, private aviation fleets, corporate boards, and fine grocers across 18 countries.</p></div><div><button onClick={() => window.alert('Preparing the FRUDEX Master Harvest Catalog.')}> <Icon>download</Icon> Master Catalog (PDF, 24MB)</button><a href="#institutional-inquiry">Initiate Trade Dialogue <Icon>arrow_forward</Icon></a></div></div></section>
  <section className="products-enquiry" id="institutional-inquiry"><div className="enquiry-card"><div className="products-centered"><Label>Direct Institutional Desk</Label><h2>Let&apos;s Connect</h2><p>Speak directly with our Master Curator for customized volume specs, harvest samples, or bespoke corporate branding allocations.</p></div><form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><div className="enquiry-fields"><label>Full Name *<input required placeholder="e.g. Eleanor Vance" /></label><label>Corporate Email *<input required placeholder="e.g. e.vance@hospitalitygroup.com" type="email" /></label><label>Direct Phone / Mobile *<input required placeholder="+1 (555) 019-2834" type="tel" /></label><label>Inquiry Domain *<select defaultValue="Institutional Procurement"><option>Institutional Procurement</option><option>Luxury Hospitality</option><option>Bespoke Corporate Gifting</option><option>Private Label &amp; Co-Branding</option></select></label></div><label>Allocation Scope / Details *<textarea required placeholder="Please outline your estimated volumes, delivery regions, and preferred harvest categories..." rows="4" /></label><div className="enquiry-submit"><span><Icon>lock</Icon> All trade inquiries handled under strict institutional confidentiality.</span><button type="submit">Send Corporate Enquiry <Icon>send</Icon></button></div>{submitted && <p className="products-success"><Icon>task_alt</Icon><strong>Inquiry Dispatched.</strong> A Frudex trade director will review your specifications.</p>}</form></div></section>
  {modal && <div className="products-modal" role="dialog" aria-modal="true"><div><button className="modal-close" onClick={() => setModal(null)}><Icon>close</Icon></button><Label>Frudex Archive Index</Label><h3>{modal.title}</h3><p>{modal.text}</p><div className="modal-spec"><span>Phytosanitary Certification: <b>ISO 22000 • BRCGS Grade AA</b></span><span>Batch Uniformity: <b>99.4% Purity Standard</b></span><span>Direct Origin: <b>Single-Estate Verified</b></span></div><div className="modal-actions"><button onClick={() => setModal(null)}>Close</button><a href="#institutional-inquiry" onClick={() => setModal(null)}>Inquire on This Spec</a></div></div></div>}
 </main>; }
